### ISSUE TITLE
code is not building in python3 

### ISSUE THREAD

**Issue by alvesadrian** [mwaskom/cregg#1]
Hello i'm trying to build this code for fedora23 pkg but it looks like your code is no compatible. do you have any suggestion to make it works in python3? like 2to3 tool or you gonna provide python3 support?

**Comment by mwaskom** [comment]
No, sorry. First, this is just a library of personal functions, not something I really intend for anyone else to use. Second, the point of the library is to build on top of Psychopy, which does not currently work on Python 3.
